spring.application.name=aethera
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/aethera
spring.datasource.username=postgres
spring.datasource.password=yash
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=12345678